version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=100
    command: npm run dev