import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { z } from "zod";

const reservarSchema = z.object({
  promo_id: z.string().uuid(),
});

export async function POST(request: Request) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "No autorizado" }, { status: 401 });
    }

    const body = await request.json();
    const result = reservarSchema.safeParse(body);

    if (!result.success) {
      return NextResponse.json({ error: result.error.issues[0].message }, { status: 400 });
    }

    const admin = createAdminClient();

    // Check active subscription
    const { data: sub } = await admin
      .from("subscriptions")
      .select("status")
      .eq("user_id", user.id)
      .eq("status", "active")
      .single();

    if (!sub) {
      return NextResponse.json({ error: "Necesitás una suscripción activa" }, { status: 403 });
    }

    // Fetch promo and global whatsapp link in parallel
    const [{ data: promo }, { data: waSetting }] = await Promise.all([
      admin
        .from("promos")
        .select("id, status, slots_taken, max_slots, title")
        .eq("id", result.data.promo_id)
        .single(),
      admin
        .from("settings")
        .select("value")
        .eq("key", "whatsapp_link")
        .single(),
    ]);

    if (!promo || promo.status !== "active") {
      return NextResponse.json({ error: "Promo no disponible" }, { status: 400 });
    }

    if (promo.slots_taken >= promo.max_slots) {
      return NextResponse.json({ error: "No quedan cupos disponibles" }, { status: 400 });
    }

    // Check no duplicate booking
    const { data: existing } = await admin
      .from("promo_bookings")
      .select("id, booking_token")
      .eq("promo_id", result.data.promo_id)
      .eq("user_id", user.id)
      .single();

    if (existing) {
      return NextResponse.json(
        { error: "Ya tenés una reserva para esta promo", booking_token: existing.booking_token },
        { status: 400 }
      );
    }

    // Atomically reserve the slot
    const { data: slotReserved } = await admin.rpc("reserve_promo_slot", {
      p_promo_id: result.data.promo_id,
    });

    if (!slotReserved) {
      return NextResponse.json({ error: "No quedan cupos disponibles" }, { status: 400 });
    }

    // Create booking (token is generated by DB default)
    const { data: booking, error: bookingError } = await admin
      .from("promo_bookings")
      .insert({
        promo_id: result.data.promo_id,
        user_id: user.id,
        status: "pending",
      })
      .select("booking_token")
      .single();

    if (bookingError || !booking) {
      // Rollback the slot increment
      await admin
        .from("promos")
        .update({ slots_taken: promo.slots_taken, status: promo.status })
        .eq("id", result.data.promo_id);

      return NextResponse.json({ error: "Error al crear la reserva" }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      booking_token: booking.booking_token,
      whatsapp_link: waSetting?.value ?? null,
      promo_title: promo.title,
    });
  } catch (error) {
    console.error("[POST /api/promos/reservar]", error);
    return NextResponse.json({ error: "Error interno" }, { status: 500 });
  }
}
